---
- name: Remove generated TLS secret template for Interconnect
  file:
    path: "{{ ar_osc_amqinterconnect_config_dest }}/amq-interconnect-tls-secret.yml"
    state: absent
  changed_when: false

- name: Remove generated user secret for Interconnect
  file:
    path: "{{ ar_osc_amqinterconnect_config_dest }}/users-secret.yml"
    state: absent
  changed_when: false
