---
- name: Remove generated TLS secret template for Interconnect
  file:
    path: "{{ _ar_osc_amqinterconnect_tls_secret_file }}"
    state: absent
  changed_when: false

- name: Remove generated user secret for Interconnect
  file:
    path: "{{ _ar_osc_amqinterconnect_user_secret_file }}"
    state: absent
  changed_when: false
