---
- name: Generate TLS secrets template for Interconnect
  template:
    src: amq-interconnect-tls-secret.yml.j2
    dest: "{{ ar_osc_amqinterconnect_config_dest }}/amq-interconnect-tls-secret.yml"
  changed_when: false # Secret files are temporary and will be removed, so this would always represent a change
  tags:
    - secrets

- name: Generate user secrets template for Interconnect
  template:
    src: users-secret.yml.j2
    dest: "{{ ar_osc_amqinterconnect_config_dest }}/users-secret.yml"
  changed_when: false
  tags:
    - secrets
