---
- name: Generate TLS secrets template for Interconnect
  template:
    src: amq-interconnect-tls-secret.yml.j2
    dest: "{{ _ar_osc_amqinterconnect_tls_secret_file }}"
  changed_when: false # Secret files are temporary and will be removed, so this would always represent a change
  tags:
    - secrets

- name: Generate user secrets template for Interconnect
  template:
    src: users-secret.yml.j2
    dest: "{{ _ar_osc_amqinterconnect_user_secret_file }}"
  changed_when: false
  tags:
    - secrets
